easy_admin:
  entities:
    Initiative:
      class: App\Entity\Initiative
      label: 'admin.label.initiatives'
      list:
        sort: 'updatedAt'
        fields:
          - { property: 'name', label: 'admin.fields.initiative_name'}
          - { property: 'description', label: 'admin.fields.description' }
          - { property: 'initiative_type', label: 'admin.fields.petition_type'}
          - { property: 'autor', label: 'admin.fields.autor' }
          - { property: 'community_group', label: 'admin.fields.community_group'}
          - { property: 'signers', label: 'admin.fields.signers' }
          - { property: 'stad', label: 'admin.fields.stat' }
          - { property: 'createdAt', label: 'admin.fields.created_at' }
          - { property: 'updatedAt', label: 'admin.fields.updated_at'}
      form:
        fields:
          - { property: 'id', label: 'admin.fields.id', type_options: { disabled: true } }
#          - { property: 'name', label: 'admin.fields.initiative_name'}
          - { property: 'description', label: 'admin.fields.description' }
          - { property: 'initiative_type', label: 'admin.fields.petition_type'}
          - { property: 'community_group', label: 'admin.fields.community_group'}
          - { property: 'autor', label: 'admin.fields.autor' }
          - { property: 'signers', label: 'admin.fields.signers' }
          - { property: 'createdAt', label: 'admin.fields.created_at', type_options: { widget: 'single_text', required: false, disabled: true } }
          - { property: 'updatedAt', label: 'admin.fields.updated_at', type_options: { widget: 'single_text', required: false, disabled: true } }